remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: Drassil/git-wiki-theme@master
# (string) Title of your wiki
title: "Wiki Title"
# (string) if you've installed your wiki in subfolder, you must change this configuration
# with your folder name, otherwise leave it empty
baseurl: "/saints"
# (string) Description of your wiki
description:
# (boolean) disable edit functionalities (edit/delete/add pages)

plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-gitlab-metadata


#
# INCLUDING HOOKS
# They are optional, change them only if you need
# Check wiki documentation to learn how they work
#

inc_before_toc : 
inc_after_toc : 
inc_before_content : 
inc_after_content : 
inc_before_footer : 
inc_after_footer : 
inc_before_head : 
inc_after_head : 
inc_before_meta : 
inc_after_meta : 
inc_before_scripts : 
inc_after_scripts : 
inc_before_styles : 
inc_after_styles : 
inc_before_header : 
inc_after_header : 
inc_before_tail : 
inc_after_tail : 
inc_before_tools : 
inc_after_tools : 

inc_before_page_list :
inc_after_page_list : sidebar.html
inc_before_post_list :
inc_after_post_list :
