title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
theme: jekyll-theme-minimal
title: [The title of your site]
description: [A short description of your site's purpose]
plugins:
- jekyll-remote-theme #

#source: wiki/


## Sidebar

---
  defaults:
    # _docs
    - scope:
        path: ""
        type: main
      values:
        sidebar:
          nav: "main"
  ---    